### ISSUE TITLE
strcmp en código de Capítulo9-Programa1.txt

### ISSUE THREAD

**Issue by OslafEman** [bitwiseAr/Curso-Arduino-desde-cero#1]
Hola bitwiseAr, felicitaciones por lo didáctico y detallado de tus cursos, son de gran ayuda para quienes nos iniciamos con las bondades de Arduino.
Me gustaría preguntar por qué en el condicional del comparador de strings del código del capítulo 9 no se abren ni se cierran las llaves "{" "}" ni en el "if" ni en el "else".
`   if(!strcmp(CLAVE, CLAVE_MAESTRA))`
`      Serial.println(" Correcta");`  
`    else`
`      Serial.println(" Incorrecta");` 
`      INDICE = 0;`
Estoy tratando de correr este código junto con una pantalla LCD y un adaptador LCD I2C (curso #35), y cuando añado las líneas "lcd.print(" Correcta");" o "lcd.print(" Incorrecta");" el compilador me pide las llaves, y cuando las añado el comportamiento del programa cambia sustancialmente.
Me gustaría entender este detalle.  Muchas gracias.

Oslaf

**Comment by bitwiseAr** [comment]
Hola, cuando el código ocupa una sola línea no es obligatorio abrir y cerrar llaves, si se fuese a colocar un bloque con más de una línea entonces si se debe delimitar con las llaves de apertura y cierre.
Saludos

**Comment by JhonathanOrtiz** [comment]
Hola amigo, tu curso me ha servido infinidad de veces y lo que he aprendido te lo debo


El problema es el siguiente he intentado programar una pantalla LCD 1602A (Backlight verde); pero no me muestra caracteres solo enciende el Backlight y quisiera saber cómo hacer un troubleshooting y descartar que sea la pantalla
