### ISSUE TITLE
Problema con MPU6050 - capitulo 65

### ISSUE THREAD

**Issue by ezequielleonzybert** [bitwiseAr/Curso-Arduino-desde-cero#5]
Hola Bitwise, gracias por tus videos. Estoy teniendo un problema con el capítulo 65 donde haces funcionar un sensor MPU6050.
Copié el código tal cual lo dejaste aquí en github, también instalé las dos librerías necesarias y a la hora de compilar me sale el error: 
`
In file included from D:\Documentos\Estudios\Artes multimediales II\TP3\proyecto\archivos\codigo_TP3\codigo_TP3.ino:13:0:
C:\Users\Ezequiel\Documents\Arduino\libraries\Simple_MPU6050-master/Simple_MPU6050.h:37:25: error: ">" may not appear in macro parameter list
 #define if(interruptPin > 0) Interupt_Attach_Function attachInterrupt(digitalPinToInterrupt(interruptPin), [] {mpuInterrupt = true;}, RISING);
                         ^
exit status 1
Error compiling for board Arduino Uno.
`

¿Tenes idea de lo que podría ser?
aquí abrí la misma pregunta en un hilo de stackOverflow con un poco más de detalle:
https://stackoverflow.com/questions/69598104/arduino-compiling-error-may-not-appear-in-macro-parameter-list
Gracias

**Comment by bitwiseAr** [comment]
Hola, lamentablemente un cambio por parte del desarrollador de la librería hace que el código genere errores, lo antes que me sea posible lo estaré revisando y replicando el error para corregirlo. Podrás utilizar la versión de la librería mencionada en el video que funciona correctamente mientras tanto. Saludos
