### ISSUE TITLE
ayuda con código de activar led con mando a distancia.

### ISSUE THREAD

**Issue by TEOACV** [bitwiseAr/Curso-Arduino-desde-cero#6]
saludos.
este es código, pero al instalarlo en el Arduino uno no hace nada, presiono el botón de power, uno, dos .... hasta 9 y no encienden.
me podrías ayudar?

#include "IRremote.h"
#define LED1 2
#define LED2 3
#define LED3 4
#define LED4 5
#define LED5 6
#define LED6 7
#define LED7 8
#define LED8 9
#define LED9 10
#define LED10 12

int receiver = 11;
IRrecv irrecv(receiver);
decode_results results;

void translateIR(){
  switch(results.value){    
  case 0xFFA25D: Serial.println("POWER");
  digitalWrite(LED1, LOW);
  digitalWrite(LED2, LOW);
  digitalWrite(LED3, LOW);
  digitalWrite(LED4, LOW);
  digitalWrite(LED5, LOW);
  digitalWrite(LED6, LOW);
  digitalWrite(LED7, LOW);
  digitalWrite(LED8, LOW);
  digitalWrite(LED9, LOW);
  digitalWrite(LED10, LOW);
  break;  
  
  case 0xFFC23D: Serial.println("FAST FORWARD");
  digitalWrite(LED1, HIGH);
  digitalWrite(LED2, HIGH);
  digitalWrite(LED3, HIGH);
  digitalWrite(LED4, HIGH);
  digitalWrite(LED5, HIGH);
  digitalWrite(LED6, HIGH);
  digitalWrite(LED7, HIGH);
  digitalWrite(LED8, HIGH);
  digitalWrite(LED9, HIGH);
  digitalWrite(LED10, HIGH);
  break;  
  
  case 0xFF6897: Serial.println("0");
  pinMode(LED1, OUTPUT);
  digitalWrite(LED1, HIGH);
  break;  
  
  case 0xFF30CF: Serial.println("1");
  pinMode(LED2, OUTPUT);
  digitalWrite(LED2, HIGH);
  break;  
  
  case 0xFF18E7: Serial.println("2");
  pinMode(LED3, OUTPUT);
  digitalWrite(LED3, HIGH);
  break;  
  
  case 0xFF7A85: Serial.println("3");
  pinMode(LED4, OUTPUT);
  digitalWrite(LED4, HIGH);
  break;  
  
  case 0xFF10EF: Serial.println("4");
  pinMode(LED5, OUTPUT);
  digitalWrite(LED5, HIGH);
  break;  
  
  case 0xFF38C7: Serial.println("5");
  pinMode(LED6, OUTPUT);
  digitalWrite(LED6, HIGH);
  break; 
   
  case 0xFF5AA5: Serial.println("6");
  pinMode(LED7, OUTPUT);
  digitalWrite(LED7, HIGH);
  break;  
  
  case 0xFF42BD: Serial.println("7");
  pinMode(LED8, OUTPUT);
  digitalWrite(LED8, HIGH);
  break;  
  
  case 0xFF4AB5: Serial.println("8");
  pinMode(LED9, OUTPUT);
  digitalWrite(LED9, HIGH);
  break;  
  
  case 0xFF52AD: Serial.println("9");
  pinMode(LED10, OUTPUT);
  digitalWrite(LED10, HIGH);
  break;  
  
  case 0xFFFFFFFF: Serial.println("ERROR");break; 
  
  default: 
    Serial.println("Otro botón");
  }
  delay(500);
}

**Comment by Szpillmann** [comment]
Hola , me parece que en define te falta el signo = para asignar la salida a tu variable led por ejemplo LED1=2 , dale una vuelta y revisa

**Comment by TEOACV** [comment]
> Hola , me parece que en define te falta el signo = para asignar la salida a tu variable led por ejemplo LED1=2 , dale una vuelta y revisa

gracias, lo revisare.

**Comment by TEOACV** [comment]
> Hola , me parece que en define te falta el signo = para asignar la salida a tu variable led por ejemplo LED1=2 , dale una vuelta y revisa

me merca este error.
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino: In function 'void translateIR()':
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:6:14: error: expected primary-expression before '=' token
 #define LED1 2
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:24:16: note: in expansion of macro 'LED1'
   digitalWrite(LED1, LOW);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:7:14: error: expected primary-expression before '=' token
 #define LED2 3
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:25:16: note: in expansion of macro 'LED2'
   digitalWrite(LED2, LOW);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:8:14: error: expected primary-expression before '=' token
 #define LED3 4
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:26:16: note: in expansion of macro 'LED3'
   digitalWrite(LED3, LOW);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:9:14: error: expected primary-expression before '=' token
 #define LED4 5
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:27:16: note: in expansion of macro 'LED4'
   digitalWrite(LED4, LOW);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:10:14: error: expected primary-expression before '=' token
 #define LED5 6
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:28:16: note: in expansion of macro 'LED5'
   digitalWrite(LED5, LOW);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:11:14: error: expected primary-expression before '=' token
 #define LED6 7
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:29:16: note: in expansion of macro 'LED6'
   digitalWrite(LED6, LOW);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:12:14: error: expected primary-expression before '=' token
 #define LED7 8
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:30:16: note: in expansion of macro 'LED7'
   digitalWrite(LED7, LOW);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:13:14: error: expected primary-expression before '=' token
 #define LED8 9
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:31:16: note: in expansion of macro 'LED8'
   digitalWrite(LED8, LOW);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:14:14: error: expected primary-expression before '=' token
 #define LED9 10
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:32:16: note: in expansion of macro 'LED9'
   digitalWrite(LED9, LOW);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:15:15: error: expected primary-expression before '=' token
 #define LED10 12
               ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:33:16: note: in expansion of macro 'LED10'
   digitalWrite(LED10, LOW);
                ^~~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:6:14: error: expected primary-expression before '=' token
 #define LED1 2
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:37:16: note: in expansion of macro 'LED1'
   digitalWrite(LED1, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:7:14: error: expected primary-expression before '=' token
 #define LED2 3
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:38:16: note: in expansion of macro 'LED2'
   digitalWrite(LED2, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:8:14: error: expected primary-expression before '=' token
 #define LED3 4
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:39:16: note: in expansion of macro 'LED3'
   digitalWrite(LED3, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:9:14: error: expected primary-expression before '=' token
 #define LED4 5
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:40:16: note: in expansion of macro 'LED4'
   digitalWrite(LED4, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:10:14: error: expected primary-expression before '=' token
 #define LED5 6
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:41:16: note: in expansion of macro 'LED5'
   digitalWrite(LED5, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:11:14: error: expected primary-expression before '=' token
 #define LED6 7
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:42:16: note: in expansion of macro 'LED6'
   digitalWrite(LED6, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:12:14: error: expected primary-expression before '=' token
 #define LED7 8
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:43:16: note: in expansion of macro 'LED7'
   digitalWrite(LED7, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:13:14: error: expected primary-expression before '=' token
 #define LED8 9
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:44:16: note: in expansion of macro 'LED8'
   digitalWrite(LED8, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:14:14: error: expected primary-expression before '=' token
 #define LED9 10
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:45:16: note: in expansion of macro 'LED9'
   digitalWrite(LED9, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:15:15: error: expected primary-expression before '=' token
 #define LED10 12
               ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:46:16: note: in expansion of macro 'LED10'
   digitalWrite(LED10, HIGH);
                ^~~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:6:14: error: expected primary-expression before '=' token
 #define LED1 2
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:50:11: note: in expansion of macro 'LED1'
   pinMode(LED1, OUTPUT);
           ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:6:14: error: expected primary-expression before '=' token
 #define LED1 2
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:51:16: note: in expansion of macro 'LED1'
   digitalWrite(LED1, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:7:14: error: expected primary-expression before '=' token
 #define LED2 3
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:55:11: note: in expansion of macro 'LED2'
   pinMode(LED2, OUTPUT);
           ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:7:14: error: expected primary-expression before '=' token
 #define LED2 3
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:56:16: note: in expansion of macro 'LED2'
   digitalWrite(LED2, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:8:14: error: expected primary-expression before '=' token
 #define LED3 4
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:60:11: note: in expansion of macro 'LED3'
   pinMode(LED3, OUTPUT);
           ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:8:14: error: expected primary-expression before '=' token
 #define LED3 4
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:61:16: note: in expansion of macro 'LED3'
   digitalWrite(LED3, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:9:14: error: expected primary-expression before '=' token
 #define LED4 5
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:65:11: note: in expansion of macro 'LED4'
   pinMode(LED4, OUTPUT);
           ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:9:14: error: expected primary-expression before '=' token
 #define LED4 5
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:66:16: note: in expansion of macro 'LED4'
   digitalWrite(LED4, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:10:14: error: expected primary-expression before '=' token
 #define LED5 6
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:70:11: note: in expansion of macro 'LED5'
   pinMode(LED5, OUTPUT);
           ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:10:14: error: expected primary-expression before '=' token
 #define LED5 6
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:71:16: note: in expansion of macro 'LED5'
   digitalWrite(LED5, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:11:14: error: expected primary-expression before '=' token
 #define LED6 7
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:75:11: note: in expansion of macro 'LED6'
   pinMode(LED6, OUTPUT);
           ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:11:14: error: expected primary-expression before '=' token
 #define LED6 7
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:76:16: note: in expansion of macro 'LED6'
   digitalWrite(LED6, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:12:14: error: expected primary-expression before '=' token
 #define LED7 8
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:80:11: note: in expansion of macro 'LED7'
   pinMode(LED7, OUTPUT);
           ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:12:14: error: expected primary-expression before '=' token
 #define LED7 8
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:81:16: note: in expansion of macro 'LED7'
   digitalWrite(LED7, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:13:14: error: expected primary-expression before '=' token
 #define LED8 9
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:85:11: note: in expansion of macro 'LED8'
   pinMode(LED8, OUTPUT);
           ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:13:14: error: expected primary-expression before '=' token
 #define LED8 9
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:86:16: note: in expansion of macro 'LED8'
   digitalWrite(LED8, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:14:14: error: expected primary-expression before '=' token
 #define LED9 10
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:90:11: note: in expansion of macro 'LED9'
   pinMode(LED9, OUTPUT);
           ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:14:14: error: expected primary-expression before '=' token
 #define LED9 10
              ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:91:16: note: in expansion of macro 'LED9'
   digitalWrite(LED9, HIGH);
                ^~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:15:15: error: expected primary-expression before '=' token
 #define LED10 12
               ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:95:11: note: in expansion of macro 'LED10'
   pinMode(LED10, OUTPUT);
           ^~~~~
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:15:15: error: expected primary-expression before '=' token
 #define LED10 12
               ^
C:\Users\TEOACV2\OneDrive\Documents\Arduino\led remoto\gdfd\gdfd.ino:96:16: note: in expansion of macro 'LED10'
   digitalWrite(LED10, HIGH);
                ^~~~~

exit status 1

Compilation error: expected primary-expression before '=' token

**Comment by TEOACV** [comment]
> Hola , me parece que en define te falta el signo = para asignar la salida a tu variable led por ejemplo LED1=2 , dale una vuelta y revisa

saludos, asi quedo el código. pero no funciona, el mando no [responde.](
![image](https://user-images.githubusercontent.com/115046839/211157094-1482e3d8-455a-4a81-a808-d08b8ec7b0c3.png)
)

#include <IRremote.hpp>

void setup() {
}
#include "IRremote.h"
#define LED1 = 2;
#define LED2 = 3;
#define LED3 = 4;
#define LED4 = 5;
#define LED5 = 6;
#define LED6 = 7;
#define LED7 = 8;
#define LED8 = 9;
#define LED9 = 10;
#define LED10 = 12;

int receiver = 11;
IRrecv irrecv(receiver);
decode_results results;

void translateIR(){
  switch(results.value)   {
  case 0xFFA25D: Serial.println("POWER");
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  digitalWrite(7, LOW);
  digitalWrite(8, LOW);
  digitalWrite(9, LOW);
  digitalWrite(10, LOW);
  digitalWrite(12, LOW);
  break;  
  
  case 0xFFC23D: Serial.println("FAST FORWARD");
  digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(12, HIGH);
  break;  
  
  case 0xFF6897: Serial.println("0");
  pinMode(2, OUTPUT);
  digitalWrite(2, HIGH);
  break;  
  
  case 0xFF30CF: Serial.println("1");
  pinMode(3, OUTPUT);
  digitalWrite(3, HIGH);
  break;  
  
  case 0xFF18E7: Serial.println("2");
  pinMode(4, OUTPUT);
  digitalWrite(4, HIGH);
  break;  
  
  case 0xFF7A85: Serial.println("3");
  pinMode(5, OUTPUT);
  digitalWrite(5, HIGH);
  break;  
  
  case 0xFF10EF: Serial.println("4");
  pinMode(6, OUTPUT);
  digitalWrite(6, HIGH);
  break;  
  
  case 0xFF38C7: Serial.println("5");
  pinMode(7, OUTPUT);
  digitalWrite(7, HIGH);
  break; 
   
  case 0xFF5AA5: Serial.println("6");
  pinMode(8, OUTPUT);
  digitalWrite(8, HIGH);
  break;  
  
  case 0xFF42BD: Serial.println("7");
  pinMode(9, OUTPUT);
  digitalWrite(9, HIGH);
  break;  
  
  case 0xFF4AB5: Serial.println("8");
  pinMode(10, OUTPUT);
  digitalWrite(10, HIGH);
  break;  
  
  case 0xFF52AD: Serial.println("9");
  pinMode(12, OUTPUT);
  digitalWrite(12, HIGH);
  break;  
  
  case 0xFFFFFFFF: Serial.println("ERROR");break; 
  
  default: 
    Serial.println("Otro botón");
  }
  delay(500);
}


void loop() {
}

**Comment by TEOACV** [comment]
![esquema](https://user-images.githubusercontent.com/115046839/211157134-ae9a1d01-a5e4-484b-8697-b199216b87f6.jpg)

**Comment by TEOACV** [comment]
![esquema](https://user-images.githubusercontent.com/115046839/211157201-c1631cd8-ce6e-4669-a46c-9c9073cab636.jpg)

**Comment by Szpillmann** [comment]
![image](https://user-images.githubusercontent.com/64436415/211167533-b7baa7c1-0e92-4b76-bff9-37dc57195f4d.jpeg)

Pues si compañero mira, dentro del void setup{ .... } va todo lo que seteas solo una vez , luego en void loop{ .... } va todo lo que se ejecuta cada ciclo del procesador, veo que dentro de setup no hay nada ya que abres corchetes { y lo cierras abajo } lo mismo en loop , abres y cierras , dentro de loop debería estar la rutina que está constantemente revisando si presionaste un botón , que me parece que es void translateir hacia abajo

**Comment by Szpillmann** [comment]
Deberías tener al final que ordenes tu código algo así![image](https://user-images.githubusercontent.com/64436415/211167759-bdce4bc4-3a3d-4413-9404-3ac58845b9a6.jpeg)
